name: "🐛 Report a bug with a concept"
description: Create a new ticket for a bug releated to a specific concept (e.g. typos, grammar etc)
title: "🐛 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: input
    id: concept
    attributes:
      label: "Data component concept"
      description: Please enter the code and description of the concept
      placeholder: e.g. 103.16183 Adequacy for Testing
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of the problem associated with the concept...
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: "Request"
      description: Please describe what you think needs to happen to address the issue
    validations:
      required: true
