name: "💡 New concept request"
description: Make a request for a new data component concept
title: "💡 [REQUEST] - <title>"
assignees: robeastwood-agency
labels: [
  "new concept"
]
body:
  - type: dropdown
    id: category
    attributes:
      label: "Concept category"
      description: What category of data component you are requesting?
      multiple: false
      options:
        - Structured Document
        - Section
        - Data group
        - Data Element
        - Choice
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Concept description"
      description: Short description of what will be identified by this code
      placeholder: "TODO"
    validations:
      required: true
  - type: input
    id: preferred_name
    attributes:
      label: "Preferred concept display"
      description: Your preferred text for the associated display of the code 
      placeholder: "TODO"
    validations:
      required: false
  - type: textarea
    id: relationship
    attributes:
      label: "Relationships to existing concepts"
      description: Describe any known relationships to existing concepts 
      placeholder: "TODO"
    validations:
      required: false
  - type: input
    id: project_name
    attributes:
      label: "Project name"
      description: The project that requires this concept
      placeholder: TODO
    validations:
      required: true
  - type: textarea
    id: project_description
    attributes:
      label: "Project description"
      description: The description of the project, is not already known
      placeholder: TODO
    validations:
      required: false
  - type: input
    id: required_date
    attributes:
      label: "Required Date"
      description: When is the concept required by
      placeholder: "day/month/year"
    validations:
      required: false
