name: "💡 Request a new concept"
description: Make a request for a new data component concept (create one issue per concept)
title: "💡 [NEW CONCEPT] - <title>"
assignees: robeastwood-agency
labels: [
  "new concept"
]
body:
  - type: markdown
    attributes:
      value: |
        ## Note
        1. Technical concepts such as those related to configuration settings will be rejected.
        2. Concepts may be found in international sources, such as LOINC, rather than be created in the NDC.
  - type: dropdown
    id: category
    attributes:
      label: "Concept category"
      description: |
        The category of data component that is being requested (i.e. document, section, element...)?
        Note that analysis may determine that a differing category may be required (i.e. what you thought was a section is actually a data group).
      multiple: false
      options:
        - Structured Document
        - Section
        - Data group
        - Data Element
        - Choice
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Concept description"
      description: Short description of what will be identified by this code
      placeholder: "description..."
    validations:
      required: true
  - type: input
    id: preferred_name
    attributes:
      label: "Preferred concept name"
      description: |
        Your preferred text for the associated display of the code.
        Note that concept name will be subject to the naming conventions of the NCTIS Data Components coding system. Where a mismatch is identified the submitter will be contacted to ensure an appropriate concept name can be registered.
    validations:
      required: true
  - type: textarea
    id: relationship
    attributes:
      label: "Relationships to existing concepts"
      description: Describe any known relationships to existing concepts 
      placeholder: "description..."
    validations:
      required: false
  - type: input
    id: project_name
    attributes:
      label: "Project name"
      description: The project that requires this concept
    validations:
      required: true
  - type: textarea
    id: project_description
    attributes:
      label: "Project description"
      description: The description of the project, if not already known
      placeholder: "description..."
    validations:
      required: false
  - type: input
    id: required_date
    attributes:
      label: "Required Date"
      description: When the concept is required by
      placeholder: "day/month/year"
    validations:
      required: false
